version: '3'

services:
  service:
    image: notification-service:0.2.1-SNAPSHOT
    ports:
      - 8080:8080
    environment:
      - S_POSTGRES_HOST=postgres
      - S_KAFKA_BOOTSTRAP_HOST=kafka:9092
      - S_POSTGRES_PASSWORD=postgres
      - S_POSTGRES_USER=postgres
    depends_on:
      - kafka
      - postgres